// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface CreativeAsset {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  kind: "source-photo" | "source-video" | "banner" | "poster" | "reel" | "story" | "gallery";
  media: { id: string; url?: string; src?: string; filename?: string; mimeType?: string; size?: number; provider?: string; meta?: Record<string, unknown> };
  event?: string;
  rights_state: "unknown" | "owner-provided" | "licensed" | "cleared";
  cleanup_state: "pending" | "passed" | "failed" | "not-required";
  source_note: string;
  legacy_path?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Event {
  id: string;
  slug: string | null;
  status: string;
  starts_at: string;
  ends_at?: string;
  event_state: "scheduled" | "postponed" | "cancelled";
  title: string;
  summary: string;
  details: PortableTextBlock[];
  title_en?: string;
  summary_en?: string;
  details_en?: PortableTextBlock[];
  title_ru?: string;
  summary_ru?: string;
  details_ru?: PortableTextBlock[];
  title_es?: string;
  summary_es?: string;
  details_es?: PortableTextBlock[];
  published_locales: ("pl" | "en" | "ru" | "es")[];
  hero_image: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  booking_url?: string;
  fact_sources: string;
  facts_confirmed_at: string;
  legacy_path?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Publication {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  channel: "instagram" | "threads" | "facebook" | "gbp";
  format: "feed" | "reel" | "story" | "text" | "gbp";
  publication_locale: "pl" | "en" | "ru" | "es";
  caption: string;
  event?: string;
  assets?: string;
  workflow_state: "draft" | "review" | "approved" | "postiz-draft" | "scheduled" | "published" | "error";
  publish_at: string;
  copy_cleanup_state: "pending" | "passed" | "failed" | "not-required";
  owner_approved_at?: string;
  postiz_id?: string;
  postiz_state?: string;
  release_url?: string;
  postiz_synced_at?: string;
  last_error?: string;
  legacy_path?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    creative_assets: CreativeAsset;
    events: Event;
    publications: Publication;
  }
}