// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface Event {
  id: string;
  slug: string | null;
  status: string;
  starts_at: string;
  ends_at?: string;
  event_state: "scheduled" | "postponed" | "cancelled";
  title: string;
  summary: string;
  details: PortableTextBlock[];
  hero_image: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  booking_url?: string;
  fact_sources: string;
  facts_confirmed_at: string;
  legacy_path?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Homepage {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  hero_image: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  hero_eyebrow?: string;
  hero_title?: string;
  hero_text?: string;
  hero_image_alt?: string;
  primary_cta_label?: string;
  secondary_cta_label?: string;
  gallery_heading?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    events: Event;
    homepage: Homepage;
  }
}