// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface Homepage {
  id: string;
  slug: string | null;
  status: string;
  name: string;
  hero_image: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  published_locales: ("pl" | "en" | "ru" | "es")[];
  hero_eyebrow_pl?: string; hero_title_pl?: string; hero_text_pl?: string; hero_image_alt_pl?: string; primary_cta_label_pl?: string; secondary_cta_label_pl?: string; gallery_heading_pl?: string;
  hero_eyebrow_en?: string; hero_title_en?: string; hero_text_en?: string; hero_image_alt_en?: string; primary_cta_label_en?: string; secondary_cta_label_en?: string; gallery_heading_en?: string;
  hero_eyebrow_ru?: string; hero_title_ru?: string; hero_text_ru?: string; hero_image_alt_ru?: string; primary_cta_label_ru?: string; secondary_cta_label_ru?: string; gallery_heading_ru?: string;
  hero_eyebrow_es?: string; hero_title_es?: string; hero_text_es?: string; hero_image_alt_es?: string; primary_cta_label_es?: string; secondary_cta_label_es?: string; gallery_heading_es?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Event {
  id: string;
  slug: string | null;
  status: string;
  starts_at: string;
  ends_at?: string;
  event_state: "scheduled" | "postponed" | "cancelled";
  title: string;
  summary: string;
  details: PortableTextBlock[];
  title_en?: string;
  summary_en?: string;
  details_en?: PortableTextBlock[];
  title_ru?: string;
  summary_ru?: string;
  details_ru?: PortableTextBlock[];
  title_es?: string;
  summary_es?: string;
  details_es?: PortableTextBlock[];
  published_locales: ("pl" | "en" | "ru" | "es")[];
  hero_image: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  booking_url?: string;
  fact_sources: string;
  facts_confirmed_at: string;
  legacy_path?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    homepage: Homepage;
    events: Event;
  }
}
